version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: 'ansi-styles'
        update-types:
          ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'got'
        update-types:
          ['version-update:semver-major', 'version-update:semver-minor']
