name: Basic validation

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  call-basic-validation:
    name: Basic validation
    env:
      INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }} # INDEXNOW_KEY env variable is only used in unit tests.
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main
